---
name: service_event
pack: service_check
description: Sample rule firing on service_check.service_event
enabled: true
trigger:
    type: service_check.service_event
criteria:
    trigger.status:
        type: nequals
        pattern: red
action:
    ref: service_check.service
    parameters:
        act: status
        service: "{{ trigger.service }}"
        hosts: sj1010010247137.corp.adobe.com
        sudo: yes
        cwd: /home/stanley/
        dir: /home/stanley/
        username: stanley
